name: Daily Stock Price Prediction

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:

jobs:
  stock_prediction:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run pipeline
      run: |
        python pipelines/fetch_and_process.py
        python pipelines/predict_new_data.py

    - name: Commit updated prediction
      run: |
        git config user.name github-actions[bot]
        git config user.email github-actions[bot]@users.noreply.github.com
        git add docs/prediction.json
        git commit -m "🔁 Daily prediction update" || echo "No changes"
        git push
