name: Daily Stock Price Prediction

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # ✅ Grant GitHub Actions permission to push changes

jobs:
  stock_prediction:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run pipeline
      run: |
        python pipelines/fetch_and_process.py
        python pipelines/predict_new_data.py

    - name: Commit updated prediction
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub's built-in authentication
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add docs/prediction.json
        git diff --quiet && git diff --staged --quiet || git commit -m "🔁 Daily prediction update"
        git push --force https://x-access-token:${GITHUB_TOKEN}@github.com/Mehedi10Rizve/stock-prediction.git HEAD:main
